// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKOEcLbqnb5foyk3fzvZottpBh7T62ZD8',
    appId: '1:912821432229:web:d32d87daa999cef33d824c',
    messagingSenderId: '912821432229',
    projectId: 'flutter-sns-app01',
    authDomain: 'flutter-sns-app01.firebaseapp.com',
    storageBucket: 'flutter-sns-app01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLXtUGon6svZAkR87UaeXFCd3qXRymjoE',
    appId: '1:912821432229:android:bbfbb501d86f7fcf3d824c',
    messagingSenderId: '912821432229',
    projectId: 'flutter-sns-app01',
    storageBucket: 'flutter-sns-app01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQFybVJVZAseNeFt16MQwK891A-8Zr5iE',
    appId: '1:912821432229:ios:3714ea0ca36928773d824c',
    messagingSenderId: '912821432229',
    projectId: 'flutter-sns-app01',
    storageBucket: 'flutter-sns-app01.appspot.com',
    iosClientId: '912821432229-ak744902srk963t07u5rhiuaqu5vkpfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppSns01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQFybVJVZAseNeFt16MQwK891A-8Zr5iE',
    appId: '1:912821432229:ios:317c350cf5c12f783d824c',
    messagingSenderId: '912821432229',
    projectId: 'flutter-sns-app01',
    storageBucket: 'flutter-sns-app01.appspot.com',
    iosClientId: '912821432229-3obhmnvrcdrs5c4b32nfhp4ffdi4uor2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAppSns01.RunnerTests',
  );
}
